server:
  image: wlniao/ngrok
  ports:
    - "8082:80"
    - "4432:443"
    - "4443:4443"
  volumes:
    - /data/ngrok:/wln
  environment:
    - DOMAIN="ngrok.wlniao.com"
  command: /bin/sh /server.sh
